import Config

# Configure your database
config :ai_with_whatsapp, AiWithWhatsapp.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "ai_with_whatsapp_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :ai_with_whatsapp, AiWithWhatsappWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Nb4i/KtW1PFS65HJEYOAP8R4j7DW8+rst+rlST6cnTon0VveYTM3+xhbx9+Jf0jm",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :whatsapp_client,
  access_token:
    "EAAFCa5ZCOZBd0BAMxal1YBa0DUJLdCsyLVJwMFQqZCF20dErxXow92ghn1iaAc5X3hr8FDh9Q9iZAsQEER0A9NWxN66Ie5VBIxuZBBRAIm1VrQnVJ8sZCMuZCssc1OhsRU68cCTDeBDAgBu9T70OKbZC5BPQwDZCvjLbnuy1Ao18mYJn08hvS5UiNm8gdj5Bx7CURZBZAAvzNVZBkVlxYjep8AS5",
  verification_token: "test",
  phone_number: "104478382289168",
  base_url: "https://graph.facebook.com/v13.0",
  hackney_pool_size: "100"

config :open_ai,
  access_key: "",
  identifier_org: "",
  base_url: "https://api.openai.com/v1",
  hackney_pool_size: "100"
